<a href="https://colab.research.google.com/github/shu65/gamma-eigen-game/blob/main/Full_batch_%CE%B3_EigenGame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


def generate_random_symmetric(n):
    a = np.random.uniform(0, 1, (n, n))
    return a + a.T - np.diag(a.diagonal())


def generate_random_symmetric_positive_definite_matrix(n):
    a = np.random.uniform(0, 1, (n, n))
    return a @ a.T

np.random.seed(0)

n = 4

A = generate_random_symmetric(n=n)
B = generate_random_symmetric_positive_definite_matrix(n=n)

A, B

(array([[0.5488135 , 1.13884417, 1.56642614, 1.11292774],
        [1.13884417, 0.64589411, 0.82102873, 1.81736964],
        [1.56642614, 0.82102873, 0.79172504, 0.59993098],
        [1.11292774, 1.81736964, 0.59993098, 0.0871293 ]]),
 array([[2.05611366, 1.72335452, 1.46862702, 1.23526515],
        [1.72335452, 2.41853727, 1.43064012, 1.56846992],
        [1.46862702, 1.43064012, 1.33643728, 1.09639162],
        [1.23526515, 1.56846992, 1.09639162, 1.11369767]]))

In [2]:
import scipy.linalg

eigenvalues, eigenvectors = scipy.linalg.eigh(A, B)
print("eigenvalues", eigenvalues)
print("eigenvectors", eigenvectors)

eigenvalues [-43.89215     -4.54359598   0.67305402   1.22805419]
eigenvectors [[-0.54526902 -1.48368166  0.15545841 -0.31741504]
 [ 2.5979192  -0.00749867  0.25072557  0.62436281]
 [ 2.12914711  1.7082045   0.06804677 -1.31352457]
 [-5.25098115  0.09931374  0.34018329  0.81282465]]


In [ ]:
# Full-batch γ-EigenGame

In [ ]:
T = int(1e5)
k = 2

vs = np.random.normal(size=(k, n,))
vs = vs / np.linalg.norm(vs, axis=1)[:, None]

eta = 1e-3
for t in range(T):
  for i in range(k):
    v_i =  vs[i, :]
    B_v_i = B @ v_i
    A_v_i = A @ v_i
    v_i_T_B_v_i = v_i.T @ B_v_i
    rewards = v_i_T_B_v_i * A_v_i - (v_i.T @ A_v_i) * B_v_i
    penalties = 0
    for j in range(i):
      v_j = vs[j, :]
      y_j = v_j / np.sqrt(v_j.T @ B @ v_j)
      B_y_j = B @ y_j
      penalties += (v_i.T @ A @ y_j) * (v_i_T_B_v_i * B_y_j - (v_i @ B_y_j) * B_v_i)
    if (t % 100) == 0:
      print("t", t, "i", i, "r", rewards, "penalties", penalties)
    d_i = rewards - penalties
    new_v_i = v_i - eta * d_i
    new_v_i /=  np.linalg.norm(new_v_i)
    vs[i, :] = new_v_i

lmds = np.empty(k,)
for i in range(k):
  v_i =  vs[i, :]
  B_v_i = B @ v_i
  A_v_i = A @ v_i
  lmds[i] = (v_i.T @ A_v_i) / (v_i.T @ B_v_i)

print("eigenvalues", lmds)
print("eigenvectors", vs)

In [42]:
T = int(1e5)
k = 2

vs = np.random.normal(size=(k, n,))
vs = vs / np.linalg.norm(vs, axis=1)[:, None]

eta = 1e-3
for i in range(k):
  for t in range(T):
    v_i =  vs[i, :]
    B_v_i = B @ v_i
    A_v_i = A @ v_i
    v_i_T_B_v_i = v_i.T @ B_v_i
    rewards = v_i_T_B_v_i * A_v_i - (v_i.T @ A_v_i) * B_v_i
    penalties = 0
    for j in range(i):
      v_j = vs[j, :]
      y_j = v_j / np.sqrt(v_j.T @ B @ v_j)
      B_y_j = B @ y_j
      penalties += (v_i.T @ A @ y_j) * (v_i_T_B_v_i * B_y_j - (v_i @ B_y_j) * B_v_i)
    if (t % 100) == 0:
      print("t", t, "i", i, "r", rewards, "penalties", penalties)
    d_i = rewards - penalties
    new_v_i = v_i - eta * d_i
    new_v_i /=  np.linalg.norm(new_v_i)
    vs[i, :] = new_v_i

lmds = np.empty(k,)
for i in range(k):
  v_i =  vs[i, :]
  B_v_i = B @ v_i
  A_v_i = A @ v_i
  lmds[i] = (v_i.T @ A_v_i) / (v_i.T @ B_v_i)

print("eigenvalues", lmds)
print("eigenvectors", vs)

t 0 i 0 r [-0.35613706 -0.48379889 -0.28596193 -0.19012169] penalties 0
t 100 i 0 r [-0.24271845 -0.27013541 -0.15378333 -0.1084258 ] penalties 0
t 200 i 0 r [-0.16295363 -0.15227237 -0.07572587 -0.04986217] penalties 0
t 300 i 0 r [-0.11296965 -0.08769526 -0.03095158 -0.01303975] penalties 0
t 400 i 0 r [-0.08307559 -0.0520819  -0.00555941  0.00864334] penalties 0
t 500 i 0 r [-0.06550302 -0.03229311  0.00876078  0.02087662] penalties 0
t 600 i 0 r [-0.05517758 -0.02123311  0.01680164  0.0275008 ] penalties 0
t 700 i 0 r [-0.04902811 -0.01502454  0.02129135  0.03088188] penalties 0
t 800 i 0 r [-0.04525947 -0.01152553  0.02377455  0.0324167 ] penalties 0
t 900 i 0 r [-0.04284074 -0.00954401  0.02512355  0.03291204] penalties 0
t 1000 i 0 r [-0.04118555 -0.00841363  0.02583024  0.03282832] penalties 0
t 1100 i 0 r [-0.03996227 -0.00776097  0.02617179  0.03242645] penalties 0
t 1200 i 0 r [-0.03898401 -0.00737656  0.0263043   0.03185363] penalties 0
t 1300 i 0 r [-0.03814574 -0.00714283